### ISSUE TITLE
Allow request result-dest to point to mounted posix volume

### ISSUE THREAD

**Issue by BenGalewsky** [ssl-hep/ServiceX_frontend#215]
_As a serviceX user I want my result files to be saved to a posix volume instead of object-store so I can use skyhook_

In order for ServiceX to write the result files to skyhook we used mounted POSIX volumes. This is a special helm chart config. The submitted requests require `result-destination` to be set to `volume`.

Currently, the value of `result-destination` is hardcoded

**Comment by oshadura** [comment]
We have finally enabled Skyhook and currently testing its functionality @ UNL coffea-casa dev instance...

According docs https://github.com/ssl-hep/ServiceX/blob/develop/docs/deployment/output_options.md#posix-mounted-volumes,  I added in the ServiceX configuration:
```
    transformer:
      persistence:
        existingClaim: skyhook-pv-claim
        subdir: /mnt/cephfs/
```
